sonar.projectKey=porteken_ai-resume-analyzer-app
sonar.organization=porteken
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**,e2e/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,src/testing,src/app.layout.tsx,src/app/error.tsx,next.config.ts

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ai-resume-analyzer-app
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
